/**
 * Stable LabOS business-operation vocabulary. Permission names describe
 * server operations rather than pages, HTTP verbs, or Organization roles.
 */
export const LABOS_PERMISSIONS = [
	'case.read',
	'case.create',
	'case.update',
	'case.archive',
	'case.assign',
	'case.transition',
	'case.financials.read',
	'case.financials.update',
	'clinic.read',
	'clinic.create',
	'clinic.update',
	'clinic.archive',
	'dentist.read',
	'dentist.create',
	'dentist.update',
	'dentist.archive',
	'patient.read',
	'patient.create',
	'patient.update',
	'patient.archive',
	'catalog.read',
	'catalog.create',
	'catalog.update',
	'catalog.archive',
	'catalog.delete',
	'staff.read',
	'staff.create',
	'staff.update',
	'staff.deactivate',
	'staff.schedule.update',
	'staff.assign',
	'staff.access.invite',
	'staff.access.revoke',
	'staff.compensation.read',
	'staff.compensation.update',
	'invoice.read',
	'invoice.create',
	'invoice.update',
	'invoice.cancel',
	'invoice.delete_draft',
	'invoice.payment.record',
	'invoice.overdue.sync',
	'payout.read',
	'payout.issue',
	'payout.void',
	'lab.settings.read',
	'lab.settings.update',
	'membership.read',
	'membership.role.update',
	'membership.remove',
	'billing.read',
	'billing.manage',
] as const

export type LabOSPermission = (typeof LABOS_PERMISSIONS)[number]
