import { createRolePermissionBundles } from '@/platform/authorization'

import { LABOS_PERMISSIONS, type LabOSPermission } from './permissions'

export const LABOS_ORGANIZATION_ROLES = [
	'owner',
	'admin',
	'manager',
	'staff',
] as const

export type LabOSOrganizationRole =
	(typeof LABOS_ORGANIZATION_ROLES)[number]

/**
 * Fixed, reviewed V1 bundles. Each role is enumerated independently: there is
 * no numeric precedence and no inheritance between roles. Adding a permission
 * to the vocabulary never grants it until the relevant bundles are reviewed.
 */
const LABOS_ROLE_PERMISSION_DEFINITIONS = {
	owner: [
		'case.read',
		'case.list',
		'case.analytics.read',
		'case.create',
		'case.update',
		'case.archive',
		'case.assign',
		'case.transition',
		'case.financials.read',
		'case.financials.list',
		'case.financials.update',
		'clinic.read',
		'clinic.list',
		'clinic.analytics.read',
		'clinic.analytics.list',
		'clinic.financials.read',
		'clinic.financials.list',
		'clinic.create',
		'clinic.update',
		'clinic.archive',
		'dentist.read',
		'dentist.list',
		'dentist.create',
		'dentist.update',
		'dentist.archive',
		'patient.read',
		'patient.list',
		'patient.create',
		'patient.update',
		'patient.archive',
		'catalog.read',
		'catalog.list',
		'catalog.analytics.read',
		'catalog.create',
		'catalog.update',
		'catalog.archive',
		'catalog.delete',
		'staff.read',
		'staff.list',
		'staff.analytics.read',
		'staff.analytics.list',
		'staff.create',
		'staff.update',
		'staff.deactivate',
		'staff.schedule.update',
		'staff.assign',
		'staff.access.invite',
		'staff.access.revoke',
		'staff.compensation.read',
		'staff.compensation.update',
		'invoice.read',
		'invoice.list',
		'invoice.analytics.read',
		'invoice.create',
		'invoice.update',
		'invoice.cancel',
		'invoice.delete_draft',
		'invoice.payment.record',
		'invoice.overdue.sync',
		'payout.read',
		'payout.list',
		'payout.issue',
		'payout.void',
		'lab.settings.read',
		'lab.settings.update',
		'membership.read',
		'membership.list',
		'membership.invite',
		'membership.role.update',
		'membership.remove',
		'billing.read',
		'billing.manage',
	],
	admin: [
		'case.read',
		'case.list',
		'case.analytics.read',
		'case.create',
		'case.update',
		'case.archive',
		'case.assign',
		'case.transition',
		'case.financials.read',
		'case.financials.list',
		'case.financials.update',
		'clinic.read',
		'clinic.list',
		'clinic.analytics.read',
		'clinic.analytics.list',
		'clinic.financials.read',
		'clinic.financials.list',
		'clinic.create',
		'clinic.update',
		'clinic.archive',
		'dentist.read',
		'dentist.list',
		'dentist.create',
		'dentist.update',
		'dentist.archive',
		'patient.read',
		'patient.list',
		'patient.create',
		'patient.update',
		'patient.archive',
		'catalog.read',
		'catalog.list',
		'catalog.analytics.read',
		'catalog.create',
		'catalog.update',
		'catalog.archive',
		'staff.read',
		'staff.list',
		'staff.analytics.read',
		'staff.analytics.list',
		'staff.create',
		'staff.update',
		'staff.deactivate',
		'staff.schedule.update',
		'staff.assign',
		'staff.access.invite',
		'staff.access.revoke',
		'staff.compensation.read',
		'invoice.read',
		'invoice.list',
		'invoice.analytics.read',
		'invoice.create',
		'invoice.update',
		'invoice.cancel',
		'invoice.delete_draft',
		'invoice.payment.record',
		'invoice.overdue.sync',
		'payout.read',
		'payout.list',
		'lab.settings.read',
		'lab.settings.update',
		'membership.read',
		'membership.list',
		'membership.invite',
		'membership.role.update',
		'membership.remove',
		'billing.read',
	],
	manager: [
		'case.read',
		'case.list',
		'case.analytics.read',
		'case.create',
		'case.update',
		'case.archive',
		'case.assign',
		'case.transition',
		'case.financials.read',
		'case.financials.list',
		'case.financials.update',
		'clinic.read',
		'clinic.list',
		'clinic.analytics.read',
		'clinic.analytics.list',
		'clinic.financials.read',
		'clinic.financials.list',
		'clinic.create',
		'clinic.update',
		'clinic.archive',
		'dentist.read',
		'dentist.list',
		'dentist.create',
		'dentist.update',
		'dentist.archive',
		'patient.read',
		'patient.list',
		'patient.create',
		'patient.update',
		'patient.archive',
		'catalog.read',
		'catalog.list',
		'catalog.analytics.read',
		'catalog.create',
		'catalog.update',
		'catalog.archive',
		'staff.read',
		'staff.list',
		'staff.analytics.read',
		'staff.analytics.list',
		'staff.create',
		'staff.update',
		'staff.deactivate',
		'staff.schedule.update',
		'staff.assign',
		'staff.compensation.read',
		'staff.compensation.update',
		'invoice.read',
		'invoice.list',
		'invoice.analytics.read',
		'invoice.create',
		'invoice.update',
		'invoice.cancel',
		'invoice.delete_draft',
		'invoice.payment.record',
		'invoice.overdue.sync',
		'payout.read',
		'payout.list',
		'payout.issue',
		'payout.void',
		'lab.settings.read',
		'billing.read',
	],
	staff: [
		'case.read',
		'case.list',
		'case.transition',
		'clinic.read',
		'clinic.list',
		'clinic.analytics.read',
		'clinic.analytics.list',
		'dentist.read',
		'dentist.list',
		'patient.read',
		'patient.list',
		'catalog.read',
		'catalog.list',
		'catalog.analytics.read',
		'staff.read',
		'staff.list',
		'staff.analytics.read',
		'staff.analytics.list',
		'invoice.read',
		'invoice.list',
		'invoice.analytics.read',
	],
} as const satisfies Readonly<
	Record<LabOSOrganizationRole, readonly LabOSPermission[]>
>

export const LABOS_ROLE_PERMISSION_BUNDLES = createRolePermissionBundles({
	roles: LABOS_ORGANIZATION_ROLES,
	permissions: LABOS_PERMISSIONS,
	bundles: LABOS_ROLE_PERMISSION_DEFINITIONS,
})

/** Role-only potential capability; resource policy evaluation remains required. */
export function roleBundleHasPermission(
	role: LabOSOrganizationRole,
	permission: LabOSPermission,
) {
	return LABOS_ROLE_PERMISSION_BUNDLES.has(role, permission)
}
