allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  prisma-zod-generator: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
